runtime: custom
env: flex

env_variables:
  ENVIRONMENT: "Linux"
  HOST: "0.0.0.0"
  GOOGLE_APPLICATION_CREDENTIALS: "credentials.json"
  INSTANCE_NAME: "comp4312-0670448:us-central1:hotel-reviews"
  BUCKET_NAME: "comp4312_hotel_reviews"
  SQL_HOST: "127.0.0.1"
  SQL_USER: "root"
  SQL_PASSWORD: "comp4312admin"
  SQL_DB: "hotel_reviews"
  
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 3
  disk_size_gb: 10
